using System.IO;
using System.Text.Json;
using EchoesUnseen.Models;

namespace EchoesUnseen.Services;

/// <summary>
/// Loads all playable songs from two sources:
///   1. <c>Songs/bundled-songs.json</c> — 6 starter songs shipped with the app
///   2. <c>%APPDATA%\EchoesUnseen\songs.json</c> — optional external library
///      generated by the gw2mb.com scraper (Scripts/DownloadSongs)
///
/// If the external file doesn't exist or fails to parse, we silently fall
/// back to the bundled songs — the app always has something to play.
///
/// The external file format matches the scraper's output schema:
///   { "version": "1.0", "source": "gw2mb.com", "songs": [ { ... }, ... ] }
///
/// Dedup: same song name + first 40 chars of ABC → keep the higher-rated one.
/// </summary>
public class SongLibraryService
{
    private readonly string _externalPath;
    private readonly string _bundledPath;

    public SongLibraryService(SettingsService settings)
    {
        _bundledPath = Path.Combine(AppContext.BaseDirectory, "Songs", "bundled-songs.json");
        _externalPath = Path.Combine(settings.AppDataDirectory, "songs.json");
    }

    /// <summary>Load all songs (bundled + external), deduplicated and sorted alphabetically.</summary>
    public List<Song> LoadAll()
    {
        var all = new List<Song>();

        // Load bundled — from the embedded copy first (so a single-file exe is
        // fully standalone), falling back to the loose file if present.
        var bundled = LoadBundled();
        if (bundled != null) all.AddRange(bundled);

        // Load external (optional)
        var external = LoadFromFile(_externalPath);
        if (external != null) all.AddRange(external);

        // Dedup by name + first 40 chars of ABC
        var deduped = all
            .GroupBy(s => $"{s.Name.ToLowerInvariant()}::{s.Abc.Substring(0, Math.Min(40, s.Abc.Length))}")
            .Select(g => g.OrderByDescending(s => s.Rating).First())
            .OrderBy(s => s.Name)
            .ToList();

        return deduped;
    }

    /// <summary>
    /// Append a song to the user's personal external library
    /// (<c>%APPDATA%\EchoesUnseen\songs.json</c>), creating the file if needed.
    /// Returns the id assigned to the new song.
    /// </summary>
    public int SaveExternalSong(string name, string instrument, int bpm, string abc)
    {
        // Read whatever is already there (or start a fresh file shape).
        SongFile doc;
        if (File.Exists(_externalPath))
        {
            try
            {
                doc = JsonSerializer.Deserialize<SongFile>(File.ReadAllText(_externalPath), JsonOpts)
                      ?? new SongFile();
            }
            catch (Exception ex)
            {
                CrashLogger.Log("SaveExternalSong read", ex);
                doc = new SongFile();
            }
        }
        else
        {
            doc = new SongFile();
        }

        doc.Version ??= "1.0";
        doc.Source ??= "personal";
        doc.Songs ??= new List<Song>();

        // Skip if a song with the same name is already in the library — stops the
        // same file being added twice (e.g. importing a folder twice). Returns -1
        // so the caller can report it as "already there" rather than "added".
        if (doc.Songs.Any(s => string.Equals(s.Name?.Trim(), name?.Trim(), StringComparison.OrdinalIgnoreCase)))
            return -1;

        // Assign an id above any existing one to avoid collisions.
        int nextId = 1000;
        if (doc.Songs.Count > 0)
            nextId = Math.Max(nextId, doc.Songs.Max(s => s.Id) + 1);

        doc.Songs.Add(new Song
        {
            Id = nextId,
            Name = name,
            Instrument = instrument,
            Bpm = bpm,
            Abc = abc,
            Source = "personal",
            Uploader = "You",
            Rating = 100,
        });

        // Make sure the folder exists, then write back.
        Directory.CreateDirectory(Path.GetDirectoryName(_externalPath)!);
        var outJson = JsonSerializer.Serialize(doc, new JsonSerializerOptions { WriteIndented = true });
        File.WriteAllText(_externalPath, outJson);
        return nextId;
    }

    /// <summary>
    /// Convert community-style number notation (keys 1-8, where 1=C … 8=high C)
    /// into the app's ABC dialect. Spaces separate notes; a dash or z is a rest.
    /// Octave markers from gw2mb-style notation (e.g. trailing 9/0 or shift
    /// markers) aren't representable on GW2's single-octave instruments, so any
    /// unrecognized character is skipped and counted in <paramref name="skipped"/>.
    /// </summary>
    /// <summary>
    /// Accept a song in EITHER format a player is likely to have and normalise it
    /// to the app's internal ABC:
    ///   • number notation (1-8), the Music-Box-site style, or
    ///   • ABC letter notation (A-G / a-g with optional durations and rests),
    ///     which most community sheet music uses.
    /// Auto-detects by whether any musical letters are present.
    /// </summary>
    public static string NormalizeUserNotation(string input, out int noteCount, out int skipped)
    {
        input ??= "";

        // RICH number notation (Vella / gw2mb "manual" style) — the format that
        // carries DEPTH: chords "1/3/6", lower-octave "[6 7 8]", rapid runs
        // "(3 2 1)", pauses "~". If any of those markers are present, parse it so
        // the chords and octaves survive instead of being flattened to single notes.
        if (input.IndexOfAny(new[] { '/', '[', ']', '(', ')', '~' }) >= 0
            && input.Any(char.IsDigit))
        {
            return FromNumberNotation(input, out noteCount, out skipped);
        }

        // KEY notation (imported GW2 songs — full three octaves): octave commands
        // 9/0 or a ".N" held-note duration mark it. Pass it straight through so the
        // octave shifts and durations survive (ParseKeyNotation reads them).
        var keyToks = input.Split(new[] { ' ', '\t', '\r', '\n', '|' }, StringSplitOptions.RemoveEmptyEntries);
        if (keyToks.Any(t => t == "9" || t == "0" || t.Contains('.') || t.Contains('=')))
        {
            noteCount = keyToks.Count(t => t.Length > 0 && t[0] >= '1' && t[0] <= '8');
            skipped = 0;
            return input.Trim();
        }

        bool hasLetters = input.Any(c => "ABCDEFGabcdefg".IndexOf(c) >= 0);
        if (!hasLetters)
            return ConvertNumberNotation(input, out noteCount, out skipped);

        noteCount = 0; skipped = 0;
        var tokens = new List<string>();
        foreach (var raw in input.Split(new[] { ' ', '\t', '\r', '\n', '|' },
                                        StringSplitOptions.RemoveEmptyEntries))
        {
            var t = raw.Trim();
            if (t.Length == 0) continue;
            char first = t[0];
            if ("ABCDEFGabcdefg".IndexOf(first) >= 0)
            {
                // Keep the note letter plus any octave marks (, ') and a trailing
                // duration; drop anything else in the token.
                var sb = new System.Text.StringBuilder();
                sb.Append(first);
                for (int i = 1; i < t.Length; i++)
                {
                    char c = t[i];
                    if (c == ',' || c == '\'' || char.IsDigit(c)) sb.Append(c);
                    else break;
                }
                tokens.Add(sb.ToString());
                noteCount++;
            }
            else if (first is 'z' or 'Z' or '-')
            {
                tokens.Add("z");
            }
            else skipped++;
        }
        return string.Join(" ", tokens);
    }

    public static string ConvertNumberNotation(string input, out int noteCount, out int skipped)
    {
        noteCount = 0;
        skipped = 0;
        var tokens = new List<string>();

        // Process character-by-character so both "1 2 3" and "123" styles work.
        foreach (var rawTok in input.Split(new[] { ' ', '\t', '\r', '\n', '|' },
                                           StringSplitOptions.RemoveEmptyEntries))
        {
            foreach (char c in rawTok)
            {
                switch (c)
                {
                    case '1': tokens.Add("C"); noteCount++; break;
                    case '2': tokens.Add("D"); noteCount++; break;
                    case '3': tokens.Add("E"); noteCount++; break;
                    case '4': tokens.Add("F"); noteCount++; break;
                    case '5': tokens.Add("G"); noteCount++; break;
                    case '6': tokens.Add("A"); noteCount++; break;
                    case '7': tokens.Add("B"); noteCount++; break;
                    case '8': tokens.Add("c"); noteCount++; break; // high C
                    case '-':
                    case 'z':
                    case 'Z': tokens.Add("z"); break;             // rest
                    default:  skipped++; break;                    // unplayable
                }
            }
        }
        return string.Join(" ", tokens);
    }

    /// <summary>
    /// Load the starter songs. Prefers the copy embedded in the assembly (so a
    /// single-file beta exe carries them with no loose Songs folder), and falls
    /// back to the on-disk Songs/bundled-songs.json for normal folder builds.
    /// </summary>
    private List<Song>? LoadBundled()
    {
        try
        {
            var asm = System.Reflection.Assembly.GetExecutingAssembly();
            var name = asm.GetManifestResourceNames()
                .FirstOrDefault(n => n.EndsWith("bundled-songs.json", StringComparison.OrdinalIgnoreCase));
            if (name != null)
            {
                using var stream = asm.GetManifestResourceStream(name);
                if (stream != null)
                {
                    using var reader = new StreamReader(stream);
                    var doc = JsonSerializer.Deserialize<SongFile>(reader.ReadToEnd(), JsonOpts);
                    if (doc?.Songs is { Count: > 0 }) return doc.Songs;
                }
            }
        }
        catch (Exception ex) { CrashLogger.Log("SongLibraryService.LoadBundled(embedded)", ex); }

        return LoadFromFile(_bundledPath); // fallback to the loose file
    }

    /// <summary>
    /// Update a song's instrument in the user's external library. If the song
    /// isn't a user song (e.g. a bundled one), it's added as a personal copy so
    /// the choice sticks. No-op-safe on any error.
    /// </summary>
    public void UpdateInstrument(string songName, string instrument)
    {
        SongFile doc;
        try
        {
            doc = File.Exists(_externalPath)
                ? JsonSerializer.Deserialize<SongFile>(File.ReadAllText(_externalPath), JsonOpts) ?? new SongFile()
                : new SongFile();
        }
        catch { doc = new SongFile(); }

        doc.Version ??= "1.0";
        doc.Source ??= "personal";
        doc.Songs ??= new List<Song>();

        var existing = doc.Songs.FirstOrDefault(s => s.Name.Equals(songName, StringComparison.OrdinalIgnoreCase));
        if (existing != null)
        {
            existing.Instrument = instrument;
        }
        else
        {
            // Copy the bundled song into the personal library with the new instrument.
            var bundled = LoadBundled()?.FirstOrDefault(s => s.Name.Equals(songName, StringComparison.OrdinalIgnoreCase));
            if (bundled == null) return;
            bundled.Instrument = instrument;
            bundled.Source = "personal";
            doc.Songs.Add(bundled);
        }

        File.WriteAllText(_externalPath, JsonSerializer.Serialize(doc, JsonOpts));
    }

    private static List<Song>? LoadFromFile(string path)
    {
        if (!File.Exists(path)) return null;
        try
        {
            var json = File.ReadAllText(path);
            var doc = JsonSerializer.Deserialize<SongFile>(json, JsonOpts);
            return doc?.Songs;
        }
        catch (Exception ex)
        {
            CrashLogger.Log($"SongLibraryService.LoadFromFile {path}", ex);
            return null;
        }
    }

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    private class SongFile
    {
        public string? Version { get; set; }
        public string? Source { get; set; }
        public List<Song>? Songs { get; set; }
    }

    // ── ABC parser ───────────────────────────────────────────────────────────
    /// <summary>
    /// Parse a song's ABC notation into a sequence of playable notes.
    /// Tolerates bars (|), octave marks (,'), and fractional durations by
    /// ignoring marks we don't support on an 8-key instrument.
    ///
    /// Duration: 1 beat = 60000 / BPM milliseconds.
    /// </summary>
    public static List<ParsedNote> ParseAbc(string abc, int bpm)
    {
        var notes = new List<ParsedNote>();
        if (string.IsNullOrWhiteSpace(abc)) return notes;

        int beatMs = 60000 / Math.Max(1, bpm);
        var tokens = abc.Split(new[] { ' ', '\t', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);

        // Auto-detect the notation. Imported GW2 songs use KEY notation (digits
        // 1-8 for the notes, 9/0 for octave-down/up), which supports the full
        // three-octave instrument. Bundled songs use single-octave ABC letters.
        int digitStart = tokens.Count(t => t.Length > 0 && char.IsDigit(t[0]));
        int letterStart = tokens.Count(t => t.Length > 0 && "ABCDEFGabcdefg".IndexOf(t[0]) >= 0);
        if (digitStart > letterStart) return ParseKeyNotation(abc, bpm);

        foreach (var raw in tokens)
        {
            if (raw == "|" || string.IsNullOrWhiteSpace(raw)) continue;

            // Strip octave marks and chord brackets
            var cleaned = raw.Replace(",", "").Replace("'", "");
            if (cleaned.StartsWith('[') && cleaned.Contains(']'))
            {
                // First note of a chord only
                var firstChar = cleaned.FirstOrDefault(c => char.IsLetter(c));
                if (firstChar != 0) cleaned = firstChar.ToString();
            }

            if (string.IsNullOrWhiteSpace(cleaned)) continue;

            var first = cleaned[0];
            bool isRest = (first == 'z' || first == 'Z');
            // Lowercase 'c' means HIGH C (instrument key 8) and must keep its
            // case — every other letter is case-insensitive. Previously this
            // line uppercased everything, which made key 8 unreachable.
            char noteChar = (first == 'c') ? 'c' : char.ToUpperInvariant(first);

            // Parse optional duration (integer after the letter)
            int beats = 1;
            if (cleaned.Length > 1 && int.TryParse(cleaned.AsSpan(1), out var parsedBeats))
                beats = Math.Clamp(parsedBeats, 1, 8);

            var key = isRest ? ' ' : NoteLetterToKey(noteChar);
            if (!isRest && key == ' ') continue; // unrecognized letter

            notes.Add(new ParsedNote(key, beatMs * beats, isRest));
        }
        return notes;
    }

    /// <summary>
    /// Parse GW2 KEY notation — the full three-octave instrument. Tokens:
    ///   1-8        a note key (one beat)
    ///   1.3        a note key held for 3 beats  (dot + beat count)
    ///   9 / 0      octave DOWN / UP command (instant; shifts the register)
    ///   z / z.2    a rest (optionally N beats)
    /// The note's Key is the literal game key, so Auto-Play reproduces the song
    /// exactly (including octave shifts), and the guide/tones read 9/0 as register
    /// changes.
    /// </summary>
    public static List<ParsedNote> ParseKeyNotation(string notation, int bpm)
    {
        var notes = new List<ParsedNote>();
        if (string.IsNullOrWhiteSpace(notation)) return notes;

        int beatMs = 60000 / Math.Max(1, bpm);
        int octaveCmdMs = Math.Clamp(beatMs / 3, 40, 200);   // an octave shift is a quick tap

        foreach (var raw in notation.Split(new[] { ' ', '\t', '\n', '\r', '|' },
                                           StringSplitOptions.RemoveEmptyEntries))
        {
            var tok = raw.Trim();
            if (tok.Length == 0) continue;
            char c = tok[0];

            if (c == '9' || c == '0')   // octave shift command
            {
                notes.Add(new ParsedNote(c, octaveCmdMs, false));
                continue;
            }

            // Exact-millisecond form "key=ms" (AutoHotkey imports keep true timing).
            int eq = tok.IndexOf('=');
            if (eq >= 0 && int.TryParse(tok.AsSpan(eq + 1), out var msVal))
            {
                msVal = Math.Clamp(msVal, 1, 60000);
                if (c is 'z' or 'Z' or '-') notes.Add(new ParsedNote(' ', msVal, true));
                else if (c >= '1' && c <= '8') notes.Add(new ParsedNote(c, msVal, false));
                continue;
            }

            // Otherwise an optional ".N" beat count (bundled ABC-style songs).
            int beats = 1;
            int dot = tok.IndexOf('.');
            if (dot >= 0 && int.TryParse(tok.AsSpan(dot + 1), out var b)) beats = Math.Clamp(b, 1, 16);

            if (c is 'z' or 'Z' or '-') { notes.Add(new ParsedNote(' ', beatMs * beats, true)); continue; }
            if (c >= '1' && c <= '8') notes.Add(new ParsedNote(c, beatMs * beats, false));
        }
        return notes;
    }

    /// <summary>
    /// Parse the RICH GW2 number notation used by community song sheets (Vella's
    /// wiki, gw2mb "manual" export) into our exact-ms KEY notation, keeping the
    /// depth:
    ///   1-8        a note
    ///   1/3/6      a CHORD — keys pressed (near-)together
    ///   [ 6 7 8 ]  LOWER octave (wrapped with the 9 = down / 0 = up shift keys)
    ///   ( 3 2 1 )  a RAPID run (each note played quicker)
    ///   ~ or -     a short pause
    /// Output tokens: "key=ms", "9"/"0" octave shifts, "z=ms" rests.
    /// </summary>
    public static string FromNumberNotation(string input, out int noteCount, out int skipped)
    {
        noteCount = 0; skipped = 0;
        var sb = new System.Text.StringBuilder();
        const int NoteMs = 300, RapidMs = 150, ChordLeadMs = 18, PauseMs = 150;

        bool rapid = false;
        int i = 0;
        while (i < input.Length)
        {
            char c = input[i];
            switch (c)
            {
                case '(': rapid = true; i++; break;
                case ')': rapid = false; i++; break;
                case '[': sb.Append("9 "); i++; break;                 // enter lower octave
                case ']': sb.Append("0 "); i++; break;                 // back up an octave
                case '~':
                case '-': sb.Append($"z={PauseMs} "); i++; break;      // short pause
                default:
                    if (c >= '1' && c <= '8')
                    {
                        // Gather a chord: 1/3/6 …
                        var chord = new List<char> { c };
                        while (i + 2 < input.Length && input[i + 1] == '/' && input[i + 2] >= '1' && input[i + 2] <= '8')
                        { chord.Add(input[i + 2]); i += 2; }

                        int dur = rapid ? RapidMs : NoteMs;
                        for (int k = 0; k < chord.Count - 1; k++)   // stacked keys, near-instant
                        { sb.Append(chord[k]).Append('=').Append(ChordLeadMs).Append(' '); noteCount++; }
                        sb.Append(chord[^1]).Append('=').Append(dur).Append(' '); noteCount++;
                        i++;
                    }
                    else { if (!char.IsWhiteSpace(c) && c != '/') skipped++; i++; }
                    break;
            }
        }
        return sb.ToString().Trim();
    }

    /// <summary>Map ABC note letter to the GW2 instrument key (1-8).</summary>
    public static char NoteLetterToKey(char letter) => letter switch
    {
        'C' => '1',
        'D' => '2',
        'E' => '3',
        'F' => '4',
        'G' => '5',
        'A' => '6',
        'B' => '7',
        'c' => '8', // high C in case it ever slips through
        _ => ' ',
    };
}
